using UnityEngine;

public class PlayerController : MonoBehaviour
{
    private const int SPEED_UNIT = 1000;
    public float speed;
    // Start is called before the first frame update
    void Start()
    {

    }

    // FixedUpdate is called once per frame
    void FixedUpdate()
    {
        if (!Global.isDialogShowing) {
            // +1 for right/up, -1 for left/down.
            // Example: Vector2(1, -1) = diagonal direction right and down.
            Vector2 direction = new Vector2(
                Input.GetAxis("Horizontal"),
                Input.GetAxis("Vertical")
            ).normalized;

            // Take the previous position and add any change to it
            // in the x and y directions.
            transform.position = new Vector2(
                transform.position.x + speed * direction.x / SPEED_UNIT,
                transform.position.y + speed * direction.y / SPEED_UNIT
            );
        }
    }
}
